export type NumberWordsLanguage = "ar" | "fr" | "en";
export type LetterCase = "normal" | "upper" | "lower";
export type DecimalSeparator = "," | ".";
export type ThousandsSeparator = "." | "," | "space" | "none";

export interface CurrencyDefinition { code: string; arMajor: string; arMajorDual: string; arMajorPlural: string; arMinor: string; arMinorDual: string; arMinorPlural: string; frMajor: string; frMinor: string; enMajor: string; enMinor: string; decimals: number; }
export interface NumberWordsOptions { language: NumberWordsLanguage; currency?: string; letterCase?: LetterCase; decimalSeparator?: DecimalSeparator; thousandsSeparator?: ThousandsSeparator; decimalPlaces?: number; writeDecimalWords?: boolean; }
export interface ParsedNumber { negative: boolean; integer: bigint; fraction: string; decimals: number; }

export const CURRENCIES: Record<string, CurrencyDefinition> = {
  DZD: { code: "DZD", arMajor: "دينار جزائري", arMajorDual: "ديناران جزائريان", arMajorPlural: "دنانير جزائرية", arMinor: "سنتيم", arMinorDual: "سنتيمان", arMinorPlural: "سنتيمات", frMajor: "dinar algérien", frMinor: "centime", enMajor: "Algerian dinars", enMinor: "centimes", decimals: 2 },
  USD: { code: "USD", arMajor: "دولار أمريكي", arMajorDual: "دولاران أمريكيان", arMajorPlural: "دولارات أمريكية", arMinor: "سنت", arMinorDual: "سنتان", arMinorPlural: "سنتات", frMajor: "dollar américain", frMinor: "cent", enMajor: "US dollars", enMinor: "cents", decimals: 2 },
  EUR: { code: "EUR", arMajor: "يورو", arMajorDual: "يوروان", arMajorPlural: "يورو", arMinor: "سنت", arMinorDual: "سنتان", arMinorPlural: "سنتات", frMajor: "euro", frMinor: "centime", enMajor: "euros", enMinor: "cents", decimals: 2 },
  GBP: { code: "GBP", arMajor: "جنيه إسترليني", arMajorDual: "جنيهان إسترلينيان", arMajorPlural: "جنيهات إسترلينية", arMinor: "بنس", arMinorDual: "بنسان", arMinorPlural: "بنسات", frMajor: "livre sterling", frMinor: "penny", enMajor: "pounds sterling", enMinor: "pence", decimals: 2 },
  MAD: { code: "MAD", arMajor: "درهم مغربي", arMajorDual: "درهمان مغربيان", arMajorPlural: "دراهم مغربية", arMinor: "سنتيم", arMinorDual: "سنتيمان", arMinorPlural: "سنتيمات", frMajor: "dirham marocain", frMinor: "centime", enMajor: "Moroccan dirhams", enMinor: "centimes", decimals: 2 },
  SAR: { code: "SAR", arMajor: "ريال سعودي", arMajorDual: "ريالان سعوديان", arMajorPlural: "ريالات سعودية", arMinor: "هللة", arMinorDual: "هللتان", arMinorPlural: "هللات", frMajor: "riyal saoudien", frMinor: "halala", enMajor: "Saudi riyals", enMinor: "halalas", decimals: 2 },
  CAD: { code: "CAD", arMajor: "دولار كندي", arMajorDual: "دولاران كنديان", arMajorPlural: "دولارات كندية", arMinor: "سنت", arMinorDual: "سنتان", arMinorPlural: "سنتات", frMajor: "dollar canadien", frMinor: "cent", enMajor: "Canadian dollars", enMinor: "cents", decimals: 2 },
};

const AR_ONES = ["صفر", "واحد", "اثنان", "ثلاثة", "أربعة", "خمسة", "ستة", "سبعة", "ثمانية", "تسعة"];
const AR_TENS = ["", "", "عشرون", "ثلاثون", "أربعون", "خمسون", "ستون", "سبعون", "ثمانون", "تسعون"];
const AR_HUNDREDS = ["", "مائة", "مائتان", "ثلاثمائة", "أربعمائة", "خمسمائة", "ستمائة", "سبعمائة", "ثمانمائة", "تسعمائة"];
const AR_SCALES = [["", "", ""], ["ألف", "ألفان", "آلاف"], ["مليون", "مليونان", "ملايين"], ["مليار", "ملياران", "مليارات"], ["تريليون", "تريليونان", "تريليونات"], ["كوادرليون", "كوادرليونان", "كوادرليونات"]];
const EN_ONES = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"];
const EN_TENS = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"];
const EN_SCALES = ["", "thousand", "million", "billion", "trillion", "quadrillion"];
const FR_ONES = ["zéro", "un", "deux", "trois", "quatre", "cinq", "six", "sept", "huit", "neuf", "dix", "onze", "douze", "treize", "quatorze", "quinze", "seize"];

function groupTriplets(value: bigint): number[] { const groups: number[] = []; let current = value; while (current > BigInt(0)) { groups.unshift(Number(current % BigInt(1000))); current /= BigInt(1000); } return groups.length ? groups : [0]; }
function arBelowThousand(value: number): string { if (value < 10) return AR_ONES[value]!; if (value === 10) return "عشرة"; if (value === 11) return "أحد عشر"; if (value === 12) return "اثنا عشر"; if (value < 20) return `${AR_ONES[value - 10]} عشر`; if (value < 100) { const one = value % 10; return one ? `${AR_ONES[one]} و${AR_TENS[Math.floor(value / 10)]}` : AR_TENS[Math.floor(value / 10)]!; } const hundred = Math.floor(value / 100); const rest = value % 100; return rest ? `${AR_HUNDREDS[hundred]} و${arBelowThousand(rest)}` : AR_HUNDREDS[hundred]!; }
function arInteger(value: bigint): string { if (value === BigInt(0)) return "صفر"; return groupTriplets(value).map((group, index, groups) => { const scale = groups.length - index - 1; if (!group) return ""; if (scale === 0) return arBelowThousand(group); const [one, dual, plural] = AR_SCALES[scale] ?? ["", "", ""]; if (group === 1) return one; if (group === 2) return dual; if (group < 11) return `${arBelowThousand(group)} ${plural}`; return `${arBelowThousand(group)} ${one}`; }).filter(Boolean).join(" و"); }
function enBelowThousand(value: number): string { const words: string[] = []; if (value >= 100) { words.push(`${EN_ONES[Math.floor(value / 100)]} hundred`); value %= 100; } if (value >= 20) { words.push(EN_TENS[Math.floor(value / 10)]!); value %= 10; } if (value > 0) words.push(EN_ONES[value]!); return words.join(" "); }
function enInteger(value: bigint): string { if (value === BigInt(0)) return "zero"; return groupTriplets(value).map((group, index, groups) => { if (!group) return ""; return `${enBelowThousand(group)}${EN_SCALES[groups.length - index - 1] ? ` ${EN_SCALES[groups.length - index - 1]}` : ""}`; }).filter(Boolean).join(" "); }
function frBelowHundred(value: number): string { if (value < 17) return FR_ONES[value]!; if (value < 20) return `dix-${FR_ONES[value - 10]}`; if (value < 70) { const tens = ["", "", "vingt", "trente", "quarante", "cinquante", "soixante"][Math.floor(value / 10)]!; const one = value % 10; return one === 1 ? `${tens} et un` : one ? `${tens}-${FR_ONES[one]}` : tens; } if (value < 80) return value === 71 ? "soixante et onze" : `soixante-${frBelowHundred(value - 60)}`; return value === 80 ? "quatre-vingts" : `quatre-vingt-${frBelowHundred(value - 80)}`; }
function frBelowThousand(value: number): string { if (value < 100) return frBelowHundred(value); const hundreds = Math.floor(value / 100); const rest = value % 100; const prefix = hundreds === 1 ? "cent" : `${FR_ONES[hundreds]} cent`; return rest ? `${prefix} ${frBelowHundred(rest)}` : prefix + (hundreds > 1 ? "s" : ""); }
function frInteger(value: bigint): string { if (value === BigInt(0)) return "zéro"; const groups = groupTriplets(value); return groups.map((group, index) => { if (!group) return ""; const scale = groups.length - index - 1; if (scale === 0) return frBelowThousand(group); if (scale === 1) return group === 1 ? "mille" : `${frBelowThousand(group)} mille`; const names = ["", "", "million", "milliard", "billion", "billiard"]; return `${frBelowThousand(group)} ${names[scale] ?? ""}${group > 1 ? "s" : ""}`; }).filter(Boolean).join(" "); }
function arabicCurrencyUnit(value: bigint, currency: CurrencyDefinition, minor = false): string { if (value === BigInt(1)) return minor ? currency.arMinor : currency.arMajor; if (value === BigInt(2)) return minor ? currency.arMinorDual : currency.arMajorDual; return minor ? (value >= BigInt(3) && value <= BigInt(10) ? currency.arMinorPlural : currency.arMinor) : (value >= BigInt(3) && value <= BigInt(10) ? currency.arMajorPlural : currency.arMajor); }
function applyCase(value: string, letterCase: LetterCase = "normal"): string { return letterCase === "upper" ? value.toLocaleUpperCase() : letterCase === "lower" ? value.toLocaleLowerCase() : value; }

export function parseNumberInput(input: string, options: Pick<NumberWordsOptions, "decimalSeparator" | "thousandsSeparator" | "decimalPlaces"> = {}): ParsedNumber {
  let value = input.trim().replace(/\u00a0/g, " "); if (!value) throw new Error("أدخل رقمًا صالحًا"); const negative = /^-/.test(value); value = value.replace(/^[+-]/, "").replace(/\s/g, "");
  const decimal = options.decimalSeparator ?? (value.includes(",") && value.includes(".") ? (value.lastIndexOf(",") > value.lastIndexOf(".") ? "," : ".") : value.includes(",") ? "," : value.includes(".") ? "." : undefined);
  if (decimal) { const escaped = decimal === "." ? "\\." : ","; const parts = value.split(decimal); if (parts.length > 2) throw new Error("صيغة الفواصل غير صالحة"); value = parts[0]! + (options.thousandsSeparator === "none" ? "" : ""); const fraction = parts[1] ?? ""; const integer = parts[0]!.replace(/[.,]/g, ""); if (!/^\d+$/.test(integer) || (fraction && !/^\d+$/.test(fraction))) throw new Error("أدخل رقمًا صالحًا"); const decimals = options.decimalPlaces ?? fraction.length; return { negative, integer: BigInt(integer || "0"), fraction: fraction.padEnd(decimals, "0").slice(0, decimals), decimals }; }
  const integer = value.replace(/[.,]/g, ""); if (!/^\d+$/.test(integer)) throw new Error("أدخل رقمًا صالحًا"); return { negative, integer: BigInt(integer || "0"), fraction: "", decimals: 0 };
}

export function convertNumberToWords(input: string, options: NumberWordsOptions): string {
  const currency = options.currency ? CURRENCIES[options.currency.toUpperCase()] : undefined; const parsed = parseNumberInput(input, options); const decimals = options.decimalPlaces ?? currency?.decimals ?? parsed.decimals; const fraction = parsed.fraction.padEnd(decimals, "0").slice(0, decimals); const sign = parsed.negative ? options.language === "ar" ? "سالب " : options.language === "fr" ? "moins " : "minus " : "";
  let result: string;
  if (options.language === "ar") { const integerWords = arInteger(parsed.integer); result = currency ? `${integerWords} ${arabicCurrencyUnit(parsed.integer, currency)}` : integerWords; if (options.writeDecimalWords !== false && fraction && Number(fraction) > 0) { const minor = BigInt(fraction); result += ` و${arInteger(minor)} ${arabicCurrencyUnit(minor, currency ?? CURRENCIES.DZD, true)}`; } }
  else if (options.language === "fr") { const integerWords = frInteger(parsed.integer); result = currency ? `${integerWords} ${currency.frMajor}${parsed.integer > BigInt(1) ? "s" : ""}` : integerWords; if (options.writeDecimalWords !== false && fraction && Number(fraction) > 0) result += ` et ${frInteger(BigInt(fraction))} ${currency?.frMinor ?? "centièmes"}${Number(fraction) > 1 ? "s" : ""}`; }
  else { const integerWords = enInteger(parsed.integer); result = currency ? `${integerWords} ${currency.enMajor}` : integerWords; if (options.writeDecimalWords !== false && fraction && Number(fraction) > 0) result += ` and ${enInteger(BigInt(fraction))} ${currency?.enMinor ?? "hundredths"}`; }
  return applyCase(`${sign}${result}`, options.letterCase);
}

export function formatNumericInput(input: string, options: Pick<NumberWordsOptions, "decimalSeparator" | "thousandsSeparator">): string { const parsed = parseNumberInput(input, options); const raw = `${parsed.integer.toString()}${parsed.fraction ? `.${parsed.fraction}` : ""}`; const [integer, fraction] = raw.split("."); const grouped = options.thousandsSeparator === "none" ? integer! : integer!.replace(/\B(?=(\d{3})+(?!\d))/g, options.thousandsSeparator === "space" ? " " : options.thousandsSeparator ?? ","); return fraction ? `${grouped}${options.decimalSeparator ?? "."}${fraction}` : grouped; }
