import { useEffect, useRef, useState } from "react";
import { Ban, Files, RotateCcw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { createBatchTasks, type BatchOutputMode, type BatchTask, type BatchStatus } from "@shared/batch";

const label: Record<BatchStatus, string> = { queued: "في الانتظار", processing: "قيد المعالجة", completed: "مكتمل", review: "يحتاج مراجعة", failed: "فشل", cancelled: "أُلغي" };
const color: Record<BatchStatus, string> = { queued: "bg-slate-100 text-slate-600", processing: "bg-blue-100 text-blue-700", completed: "bg-emerald-100 text-emerald-700", review: "bg-amber-100 text-amber-700", failed: "bg-rose-100 text-rose-700", cancelled: "bg-slate-100 text-slate-500" };

export function BatchPanel({ onProcess, onOpenResult, destination, onBatchComplete }: { onProcess: (file: File, taskId: string, done: (status: BatchStatus, error?: string) => void, outputMode: BatchOutputMode) => Promise<void>; onOpenResult?: (review: boolean) => void; destination: "Word" | "Excel"; onBatchComplete?: (outputMode: BatchOutputMode) => Promise<void> }) {
  const [tasks, setTasks] = useState<BatchTask[]>([]);
  const [files, setFiles] = useState<File[]>([]);
  const [running, setRunning] = useState(false);
  const [outputMode, setOutputMode] = useState<BatchOutputMode>(destination === "Word" ? "separate" : "file-sheets");
  const cancelled = useRef<Set<string>>(new Set());
  useEffect(() => setOutputMode(destination === "Word" ? "separate" : "file-sheets"), [destination]);
  const choose = (selected: File[]) => { cancelled.current.clear(); setFiles(selected); setTasks(createBatchTasks(selected)); };
  const update = (id: string, status: BatchStatus, error?: string) => setTasks(current => current.map(task => task.id === id ? { ...task, status, error } : task));
  const run = async () => { if (!files.length || running) return; setRunning(true); for (const task of tasks) { if (cancelled.current.has(task.id) || task.status === "completed") continue; const file = files.find(item => `${item.name}` === task.fileName); if (!file) continue; update(task.id, "processing"); await onProcess(file, task.id, (status, error) => { if (!cancelled.current.has(task.id)) update(task.id, status, error); }, outputMode); } await onBatchComplete?.(outputMode); setRunning(false); };
  return <Card className="border-slate-200 bg-white shadow-sm"><CardHeader><div className="flex items-center justify-between"><CardTitle className="flex items-center gap-2 text-base"><Files className="size-4 text-indigo-600" /> تحويل عدة ملفات</CardTitle><Badge variant="outline">{tasks.length} ملفات</Badge></div></CardHeader><CardContent className="space-y-3"><label className="flex cursor-pointer items-center justify-between rounded-xl border border-dashed border-indigo-200 bg-indigo-50/30 p-3 text-sm"><span>اختر PDF أو صورًا متعددة</span><input type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.tiff,.webp" className="sr-only" onChange={e => choose(Array.from(e.target.files ?? []))} /></label><div className="rounded-xl border border-slate-100 bg-slate-50 p-3 text-xs"><p className="mb-2 font-semibold text-slate-600">طريقة حفظ النتائج</p><div className="grid gap-2 sm:grid-cols-3">{(destination === "Word" ? [["separate", "ملف Word لكل مصدر"], ["combined", "Word واحد مدمج"]] : [["separate", "Excel لكل مصدر"], ["combined", "Excel واحد مدمج"], ["file-sheets", "Worksheet لكل ملف"]]).map(([value, text]) => <Button key={value} size="sm" type="button" variant="outline" className={outputMode === value ? "border-indigo-300 bg-indigo-50 text-indigo-700" : "bg-white"} onClick={() => setOutputMode(value as BatchOutputMode)}>{text}</Button>)}</div></div>{tasks.length > 0 && <div className="max-h-52 divide-y rounded-xl border text-xs">{tasks.map(task => <div key={task.id} className="flex items-center justify-between gap-2 p-2"><span className="min-w-0 truncate">{task.fileName}</span><span className="flex items-center gap-2"><Badge className={color[task.status]}>{label[task.status]}</Badge>{(task.status === "completed" || task.status === "review") && <Button size="sm" variant="ghost" onClick={() => onOpenResult?.(task.status === "review")}>{task.status === "review" ? "فتح المراجعة" : "فتح النتيجة"}</Button>}{task.status === "failed" && <Button size="icon" variant="ghost" onClick={() => { cancelled.current.delete(task.id); update(task.id, "queued"); }} aria-label="إعادة المحاولة"><RotateCcw className="size-3" /></Button>}{task.status !== "completed" && task.status !== "cancelled" && <Button size="icon" variant="ghost" onClick={() => { cancelled.current.add(task.id); update(task.id, "cancelled"); }} aria-label="إلغاء"><Ban className="size-3" /></Button>}</span>{task.error && <span className="block text-rose-600">{task.error}</span>}</div>)}</div>}<Button className="w-full" onClick={run} disabled={!tasks.length || running}>{running ? "جارٍ تنفيذ قائمة المهام..." : "بدء التحويل الجماعي"}</Button><p className="text-[11px] leading-5 text-slate-500">تُعالج الملفات بالتتابع للحفاظ على استجابة Task Pane، ولا يُستبدل الملف الأصلي.</p></CardContent></Card>;
}
