import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Pencil, ShieldAlert } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import type { VerificationIssue, VerificationReport } from "@shared/verification";

export function VerificationPanel({ report, sourceFile }: { report: VerificationReport; sourceFile?: File | null }) {
  const [sourceUrl, setSourceUrl] = useState<string | null>(null);
  useEffect(() => { if (!sourceFile) { setSourceUrl(null); return; } const url = URL.createObjectURL(sourceFile); setSourceUrl(url); return () => URL.revokeObjectURL(url); }, [sourceFile]);
  const [selectedId, setSelectedId] = useState<string | null>(report.issues[0]?.id ?? null);
  const [reviewed, setReviewed] = useState<Set<string>>(new Set());
  const [correctionLog, setCorrectionLog] = useState<Array<{ before: string; after: string; method: string }>>([]);
  const selected = useMemo(() => report.issues.find((item) => item.id === selectedId), [report.issues, selectedId]);
  const [draft, setDraft] = useState(selected?.extractedText ?? "");
  const openIssues = report.issues.filter((item) => !reviewed.has(item.id));
  const levelLabel = (level: VerificationIssue["level"]) => level === "trusted" ? "موثوق" : level === "review" ? "يحتاج مراجعة" : "عالي الخطورة";
  const levelClass = (level: VerificationIssue["level"]) => level === "trusted" ? "bg-emerald-100 text-emerald-700" : level === "review" ? "bg-amber-100 text-amber-700" : "bg-rose-100 text-rose-700";
  const selectIssue = (issue: VerificationIssue) => { setSelectedId(issue.id); setDraft(issue.extractedText); };
  const recordReview = (method: string, after: string) => { if (!selected) return; setReviewed((current) => new Set(current).add(selected.id)); setCorrectionLog((current) => [...current, { before: selected.extractedText, after, method }]); };
  const markReviewed = () => { if (selected) recordReview("user-accept", draft); };
  const localReOcr = () => { if (!selected) return; const after = selected.suggestion ?? selected.extractedText; setDraft(after); recordReview("local-re-ocr", after); };
  const acceptTrusted = () => setReviewed((current) => new Set(Array.from(current).concat(report.issues.filter((item) => item.level === "trusted").map((item) => item.id))));

  return <Card className="border-indigo-100 bg-indigo-50/30 shadow-none">
    <CardHeader className="pb-3"><div className="flex items-center justify-between gap-3"><CardTitle className="text-base">مراجعة التحويل</CardTitle><Badge variant="outline" className="border-indigo-200 bg-white text-indigo-700">{report.summary.overallConfidence.toFixed(1)}%</Badge></div></CardHeader>
    <CardContent className="space-y-4">
      <div className="grid gap-3 lg:grid-cols-2"><div className="min-h-32 overflow-hidden rounded-xl border border-slate-200 bg-slate-50"><div className="border-b border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-600">المصدر</div>{sourceUrl && sourceFile?.type === "application/pdf" ? <iframe title="معاينة المصدر" src={sourceUrl} className="h-48 w-full" /> : sourceUrl && sourceFile?.type.startsWith("image/") ? <img src={sourceUrl} alt="المصدر" className="max-h-48 w-full object-contain p-2" /> : <p className="p-4 text-xs leading-6 text-slate-500">المصدر محفوظ محليًا. يمكن مراجعة النص المستخرج بجانبه دون رفع ملف إضافي.</p>}</div><div className="min-h-32 rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600">الناتج المستخرج</div><p className="max-h-48 overflow-auto whitespace-pre-wrap p-3 text-xs leading-6 text-slate-700">{report.issues.length ? report.issues.slice(0, 4).map((item) => item.extractedText || "[خلية فارغة]").join("\n") : "لا توجد قضايا معروضة."}</p></div></div><div className="grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><Metric label="الكلمات" value={report.summary.totalWords} icon={<CheckCircle2 />} /><Metric label="الخلايا" value={report.summary.totalCells} icon={<Pencil />} /><Metric label="يحتاج مراجعة" value={report.summary.needsReview} icon={<AlertTriangle />} /><Metric label="عالي الخطورة" value={report.summary.highRisk} icon={<ShieldAlert />} /></div>
      {report.issues.length === 0 ? <div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">لم تُكتشف إشارات تستدعي المراجعة في هذا التحويل.</div> : <div className="grid gap-4 lg:grid-cols-[.9fr_1.1fr]"><div className="max-h-56 space-y-2 overflow-auto rounded-xl border border-indigo-100 bg-white p-2">{report.issues.map((issue) => <button key={issue.id} type="button" onClick={() => selectIssue(issue)} className={`flex w-full items-start justify-between gap-2 rounded-lg p-2 text-right text-xs transition ${selectedId === issue.id ? "bg-indigo-50 ring-1 ring-indigo-200" : "hover:bg-slate-50"} ${reviewed.has(issue.id) ? "opacity-50" : ""}`}><span className="min-w-0"><span className="block truncate font-medium">{issue.location ?? "عنصر نصي"} · {issue.extractedText || "خلية فارغة"}</span><span className="mt-1 block truncate text-slate-500">{issue.reasons.join(" · ")}</span></span><Badge className={levelClass(issue.level)}>{levelLabel(issue.level)}</Badge></button>)}</div><div className="rounded-xl border border-indigo-100 bg-white p-3">{selected ? <><div className="mb-2 flex items-center justify-between"><span className="text-xs text-slate-500">صفحة {selected.page ?? "—"} · الثقة {(selected.confidence * 100).toFixed(0)}%</span>{selected.suggestion && <Badge variant="outline" className="border-amber-200 text-amber-700">اقتراح: {selected.suggestion}</Badge>}</div><p className="mb-1 text-xs font-medium text-slate-500">الناتج الحالي</p><Textarea value={draft} onChange={(event) => setDraft(event.target.value)} className="min-h-20 bg-slate-50 text-sm" /><p className="mt-2 text-xs text-slate-500">{selected.reasons.join(" · ")}. لا يُعدّل المصدر تلقائيًا. إعادة OCR المحلية تطبق التطبيع المقترح فقط عند توفره.</p><div className="mt-3 flex gap-2"><Button type="button" size="sm" onClick={markReviewed}>قبول / اعتماد</Button><Button type="button" size="sm" variant="outline" onClick={() => recordReview("user-correction", draft)}>حفظ التعديل</Button><Button type="button" size="sm" variant="ghost" onClick={localReOcr}>إعادة OCR محليًا</Button></div></> : <p className="text-sm text-slate-500">اختر عنصرًا من قائمة المراجعة.</p>}</div></div>}
      <div className="flex flex-wrap items-center justify-between gap-2"><p className="text-[11px] text-slate-500">العناصر المفتوحة: {openIssues.length} · التعديلات لا تغيّر المصدر الأصلي.</p><Button type="button" size="sm" variant="outline" onClick={() => { acceptTrusted(); setCorrectionLog((current) => [...current, ...report.issues.filter((item) => item.level === "trusted").map((item) => ({ before: item.extractedText, after: item.extractedText, method: "accept-trusted" }))]); }}>قبول كل الموثوق</Button></div>{correctionLog.length > 0 && <div className="rounded-xl border border-slate-200 bg-white p-3"><p className="mb-2 text-xs font-semibold text-slate-600">سجل التصحيحات المحلية</p><div className="space-y-1 text-[11px] text-slate-500">{correctionLog.map((entry, index) => <p key={`${entry.method}-${index}`}>{entry.method}: {entry.before || "[فارغ]"} ← {entry.after || "[فارغ]"}</p>)}</div></div>}
    </CardContent>
  </Card>;
}
function Metric({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <div className="rounded-lg bg-white p-2"><div className="flex items-center gap-1 text-slate-400 [&>svg]:size-3">{icon}<span>{label}</span></div><strong className="mt-1 block text-sm text-slate-800">{value}</strong></div>; }
